echo 'Exporting timeline of samples...'
python tools.py export-samples-timeline data/chicago/samples-timeline.json ../data/instagram-url/chicago/*merged.csv
python tools.py export-samples-timeline data/istanbul/samples-timeline.json ../data/instagram-url/istanbul/*merged.csv
python tools.py export-samples-timeline data/london/samples-timeline.json ../data/instagram-url/london/*merged.csv
python tools.py export-samples-timeline data/new_york/samples-timeline.json ../data/instagram-url/new_york/*merged.csv
python tools.py export-samples-timeline data/paris/samples-timeline.json ../data/instagram-url/paris/*merged.csv
python tools.py export-samples-timeline data/sao_paulo/samples-timeline.json ../data/instagram-url/sao_paulo/*merged.csv
python tools.py export-samples-timeline data/sydney/samples-timeline.json ../data/instagram-url/sydney/*merged.csv
python tools.py export-samples-timeline data/tokyo/samples-timeline.json ../data/instagram-url/tokyo/*merged.csv
echo 'Exporting coords of places...'
python tools.py export-places-coords data/chicago/places-coords.json ../data/instagram-url/chicago/*merged.csv
python tools.py export-places-coords data/istanbul/places-coords.json ../data/instagram-url/istanbul/*merged.csv
python tools.py export-places-coords data/london/places-coords.json ../data/instagram-url/london/*merged.csv
python tools.py export-places-coords data/new_york/places-coords.json ../data/instagram-url/new_york/*merged.csv
python tools.py export-places-coords data/paris/places-coords.json ../data/instagram-url/paris/*merged.csv
python tools.py export-places-coords data/sao_paulo/places-coords.json ../data/instagram-url/sao_paulo/*merged.csv
python tools.py export-places-coords data/sydney/places-coords.json ../data/instagram-url/sydney/*merged.csv
python tools.py export-places-coords data/tokyo/places-coords.json ../data/instagram-url/tokyo/*merged.csv
echo 'Exporting timelines of places...'
python tools.py export-places-timeline data/chicago/places-timeline.json ../data/instagram-url/chicago/*merged.csv
python tools.py export-places-timeline data/istanbul/places-timeline.json ../data/instagram-url/istanbul/*merged.csv
python tools.py export-places-timeline data/london/places-timeline.json ../data/instagram-url/london/*merged.csv
python tools.py export-places-timeline data/new_york/places-timeline.json ../data/instagram-url/new_york/*merged.csv
python tools.py export-places-timeline data/paris/places-timeline.json ../data/instagram-url/paris/*merged.csv
python tools.py export-places-timeline data/sao_paulo/places-timeline.json ../data/instagram-url/sao_paulo/*merged.csv
python tools.py export-places-timeline data/sydney/places-timeline.json ../data/instagram-url/sydney/*merged.csv
python tools.py export-places-timeline data/tokyo/places-timeline.json ../data/instagram-url/tokyo/*merged.csv
echo 'Exporting details of places...'
python tools.py export-places-details data/chicago/places-details.json ../data/instagram-url/chicago/*merged.csv
python tools.py export-places-details data/istanbul/places-details.json ../data/instagram-url/istanbul/*merged.csv
python tools.py export-places-details data/london/places-details.json ../data/instagram-url/london/*merged.csv
python tools.py export-places-details data/new_york/places-details.json ../data/instagram-url/new_york/*merged.csv
python tools.py export-places-details data/paris/places-details.json ../data/instagram-url/paris/*merged.csv
python tools.py export-places-details data/sao_paulo/places-details.json ../data/instagram-url/sao_paulo/*merged.csv
python tools.py export-places-details data/sydney/places-details.json ../data/instagram-url/sydney/*merged.csv
python tools.py export-places-details data/tokyo/places-details.json ../data/instagram-url/tokyo/*merged.csv
